package com.example.lol

import java.lang.reflect.Constructor

object ContentCerita {

    val array = arrayOf<Cerita>(
        Cerita(0, BUDAYA, "Timun Mas", "Pada suatu hari, di sebuah desa di daerah Jawa Tengah, ada seorang janda paruh baya yang tinggal sendirian. Wanita tua ini bernama Mbok Srini, suaminya sudah meninggal sejak lama dan ia tidak memiliki anak. Mbok Srini menghabiskan hari-harinya seorang diri dan setiap harinya ia merasa bosan serta jenuh karena ia tidak memiliki seseorang untuk menemaninya.\n" +
                "Mbok Srini sejak dulu sangat ingin punya anak. Namun, impiannya yang satu ini memang tidak pernah bisa terwujud. Ditambah lagi, sekarang ia tidak memiliki seorang suami, kemungkinan ia memiliki anak pun tentu saja menjadi hilang. Mbok Srini hanya bisa menunggu keajaiban menghampirinya agar ia bisa memiliki anak. Mbok Srini selalu berdoa pada Tuhan tiap pagi, siang, dan malam hari agar Tuhan bisa melihatnya dan mengkaruniakan Mbok Srini seorang anak.\n" +
                "Lalu, pada suatu malam, Mbok Srini memimpikan seorang raksasa yang menyuruhnya pergi mengambil sebuah bungkusan di bawah pohon besar di hutan tempat biasanya ia mencari kayu bakar. Saat ia terbangun di pagi hari, tentu saja Mbok Srini merasa kebingungan dengan arti mimpi itu. Dengan berbagai keraguan dan rasa penasaran di benaknya, Mbok Srini tetap berjalan ke hutan dan mengikuti perasaannya. Saat ia tiba di hutan ia mencari bungkusan yang berada di bawah pohon besar—seperti yang ada di mimpinya semalam.\n" +
                "Sebenarnya, Mbok Srini berharap bungkusan yang hendak ia temukan ini berisi bayi, tapi yang justru ia temukan hanyalah sebutir biji timun. Hatinya pun kecewa dan merasa sedih. Tiba-tiba, ada seorang raksasa yang menghampirinya sambil tertawa terbahak-bahak. “Apa maksudmu memberikanku sebutir biji timun?” Tanya Mbok Srini seraya berteriak tapi tetap menahan emosinya. Saat Mbok Srini memperhatikan raksasa itu, ternyata raksasa itulah yang semalam menghampirinya.\n" +
                "Mbok Srini pun merasa ketakutan, ia merasa raksasa itu akan memakannya. Mbok Srini pun memohon agar raksasa itu merasa iba dan membiarkannya tetap hidup. “Tenang, jangan takut. Aku tidak akan memakanmu, wanita tua!” Ucap raksasa itu. Ternyata, raksasa ini meminta Mbok Srini menanam biji timun yang ia berikan. Katanya, ia akan dihadiahkan seorang anak perempuan jika ia menanamnya. Namun, saat anak itu sudah dewasa, Mbok Srini harus memberikan anak itu kembali pada raksasa karena ia akan memakannya. Karena Mbok Srini sangat menginginkan seorang anak, ia menyetujui perjanjian itu.\n" +
                "Saat kembali ke rumah, Mbok Srini menanam biji timun itu ke ladang rumahnya. Mbok Srini merawat biji timun itu dengan sangat baik tiap harinya. Dua bulan kemudian, tanaman itu pun mulai berubah, dan tanaman timun itu hanya berbuah satu. Semakin hari, buah timun spesial ini menjadi semakin besar, lebih besar dari buah timun pada umumnya. Warnanya pun menunjukkan warna kuning keemasan, terlihat cantik.\n" +
                "Saat buah timun itu sudah sangat besar, Mbok Srini memetiknya dan saat terbelah, ada seorang bayi perempuan yang sangat cantik. Mbok Srini sangat bahagia mendengar suara tangisan bayi itu. Ia pun memberikan nama Timun Mas. Mbok Srini merasa sangat senang sehingga ia lupa bahwa ia pernah membuat janji pada raksasa ia akan memberikan bayi ini padanya suatu hari nanti. Mbok Srini membesarkan Timun Mas dengan kasih sayang dan kesabaran. Timun Mas tumbuh menjadi seorag perempuan yang cantik, baik, serta sangat cerdas.\n" +
                "Pada suatu malam, Mbok Srini kembali bermimpi didatangi raksasa yang memberikan pesan bahwa dalam waktu seminggu, ia akan menjemput Timun Mas. Sejak saat itu, Mbok Srini sering termenung sedih sendirian. Ia terus memikirkan bahwa ia akan berpisah dengan anaknya yang sangat ia sayangi. Terkadang, air mata jatuh ke pipinya tanpa ia sadari. Ternyata, Timun Mas sering memperhatikan ibunya yang sedih ini, lalu ia pun bertanya pada Mbok Srini, “Ibu, kenapa akhir-akhir ini Ibu sering sekali menangis?” Awalnya, Mbok Srini tidak ingin bercerita pada anaknya, tapi karena Timun Mas mendesaknya dan terus bertanya, Mbok Srini pun menceritakan kisah asli kelahiran Timun Mas. Mbok Srini juga menceritakan bagian bahwa ia harus mengembalikan Timun Mas ke seorang raksasa dan beberapa malam sebelumnya raksasa itu menghampiri ia kembali ke dalam mimpi.\n" +
                "Timun Mas pun merasa sedih dan ia tidak ingin Mbok Srini mengembalikannya ke sang raksasa. Akhirnya mereka berdua berpikir dan mencari cara agar Timun Mas bisa bebas dari sang raksasa. Di hari Timun Mas harus dikembalikan, tiba-tiba Mbok Srini terpikir sebuah cara. Mbok Srini meminta Timun Mas berpura-pura sakit agar sang raksasa tidak ingin memakannya. Beruntung, car aini cukup berhasil untuk mengulur waktu, sang raksasa akan datang kembali saat Timun Mas sudah sembuh.\n" +
                "Sebelum rakasasa itu datang kembali, Mbok Srini memikirkan bagaimana cara agar anaknya bisa terbebaskan. Paginya, Mbok Srini bertemu seorang pertama di gunung, ia adalah teman suaminya yang sudah meninggal. Sesampainya di sana, Mbok Srini langsung menceritakan soal kondisinya dan ia ingin mengusir raksasa itu. Sang pertapa itu memberikan Mbok Srini empat bungkusan kecil. Katanya, bungkusan-bungkusan ini berisi biji timun, jarum, garam, dan terasi. Sang pertapa menyuruhnya memberikan empat bungkusan ini pada anaknya dan jika sang raksasa mengejarnya, sebarkan isi bungkusan-bungkusan ini.\n" +
                "Setelah itu, Mbok Srini pun pulang dengan perasaan sedikit lega, setidaknya ia sekarang sudah memiliki rencana. Beberapa hari kemudian, raksasa ini datang kembali untuk menjemput Timun Mas. Mbok Srini dan Timun Mas pun berdiri berdampingan tanpa rasa takut. Timun Mas tiba-tiba berlari sekencang-kencangnya dan raksasa itu mengejarnya. Setelah berlari cukup jauh Timun Mas menaburkan biji yang diberikan ibunya. Sungguh ajaib, hutan di sekelilingnya tiba-tiba berubah menjadi ladang timun. Dalam sekejap, batang timun tersebut menjalar dan melilit seluruh tubuh raksasa itu. Namun, raksasa itu mampu melepaskan diri dan kembali mengejar Timun Mas.\n" +
                "Timun Emas pun segera melemparkan bungkusan yang berisi jarum. Dalam sekejap, jarum-jarum berubah menjadi banyak pohon bambu yang tinggi dan runcing. Namun, raksasa itu mampu melewatinya dan terus mengejar Timun Mas, walau berdarah-darah karena tertusuk bambu tersebut.\n" +
                "Melihat usahanya belum berhasil, Timun Mas membuka bungkusan ketiga yang berisi garam lalu menebarkannya. Seketika itu pula, hutan yang telah dilewatinya tiba-tiba berubah menjadi lautan luas dan dalam, namun raksasa itu tetap berhasil melaluinya dengan mudah. Timun Emas pun cemas, karena senjatanya hanya tersisa satu. Jika senjata tersebut tidak berhasil melumpuhkan raksasa itu, maka raksasa itu akan berhasil menangkap dan memakannya.\n" +
                "Dengan harapan untuk selamat yang sangat besar, Timun Mas pun melemparkan bungkusan terakhir yang berisi terasi. Seketika tempat jatuhnya terasi itu tiba-tiba berubah menjadi lautan lumpur yang mendidih. Raksasa itu pun terkalahkan karena tercebur ke dalam lautan lumpur dan ia tewas dengan sangat cepat.\n" +
                "Melihat itu, Timun Mas langsung berlari menuju ke rumahnya untuk bertemu dengan ibunya. Melihat anaknya selamat, Mbok Srini pun langsung berucap syukur kepada Tuhan dan sejak itu, Mbok Srini dan Timun Mas hidup berbahagia.\n", R.drawable.timun_mas),
        Cerita(1, BUDAYA, "Cinderelas", "Pada suatu hari, di Jawa Timur, Indonesia, ada sebuah kerajaan yang bernama Kerajaan Jenggala. Sang Prabu di kerajaan itu bernama Raden Putra, ia memiliki seorang permaisuri dan seorang selir. Raden Putra sangat menyayangi permaisurinya, dan di saat yang bersamaan, ia juga sangat menyayangi selirnya. Selir Raden Putra tidak merasa puas dengan kedudukannya sekarang, ia merasa “kalah” dari permaisuri, apalagi ia mendapat kabar dari seorang tabib istana, bahwa kini permaisuri sedang mengandung anak Raden Putra. Sang selir berpikir ia akan semakin dilupakan oleh Raden Putra ketika anaknya lahir nanti.\n" +
                "Lalu, sang selir diam-diam menyusun sebuah rencana jahat. Ia memanggil tabib istana untuk bekerja sama dan menyingkirkan permaisuri dari istana. Jika rencana ini berhasil, sang selir akan memberikan tabib hadiah istimewa. Lalu, pada suatu hari, sang selir sakit keras, Raden Putra pun kebingungan dan merasa sedih, ia memanggil dan meminta tabib istana mempersiapkan pengobatan dan perawatan yang terbaik untuk selirnya.\n" +
                "Tabib istana berkata bahwa sang selir sakit karena ia meminum racun dan sang selir pun memperkuat perkataan tabib dengan berkata ia merasa diracun oleh permaisuri. Mendengar hal ini, Raden Putra pun marah dan memanggil permaisurinya untuk dihukum. Raden Putra memerintahkan patih istana untuk membunuh permaisuri yang sudah meracuni selir di hutan yang ada di tepi Kerajaan Jenggala. Sang permaisuri mencoba membela diri, tapi ia tidak juga dipercaya.\n" +
                "Saat permaisuri dibawa menuju ke hutan, sang selir sudah merasa lebih baik dan sembuh. Tentu saja sebenarnya mengobati selir tidak sulit karena ini semua sudah direncanakan olehnya dan tabib istana. Tabib istana sudah memiliki obat penawarnya sejak awal. Kerja sama jahat mereka pun berhasil dan sang selir akhirnya diangkat menjadi permaisuri. Seperti janji selir pada tabib istana, ia menerima uang, emas, dan barang-barang berharga lainnya.\n" +
                "Patih kerajaan yang mengetahui bagaimana sebenarnya sifat permaisuri yang baru ini yakin bahwa permaisuri yang lama tidak melakukan kejahatan. Ia percaya dengan permaisuri yang lama. Tidak mungkin wanita seagung permaisuri melakukan kekejian untuk meracun selir. Justru patih curiga bahwa selirlah yang telah memfitnah permaisuri untuk menyingkirkannya. Walaupun demikian, tentu patih kerajaan tidak mempunyai kemampuan untuk menyelematkan permaisuri dari fitnah itu.\n" +
                "Saat sampai di hutan, patih tidak menghukum mati permaisuri, ia justru membuatkan sebuah pondok yang kokoh dan nyaman untuk permaisuri tinggal. Ia juga memberikan beberapa makanan yang cukup untuk beberapa hari. Permaisuri pun sangat berterima kasih, ia justru mengkhawatirkan patih karena ia membohongi Raden Putra. Patih mengatakan bahwa permaisuri tidak perlu khawatir, ia akan menggunakan darah rusa sebagai bukti pada istana bahwa ia sudah membunuh permaisuri.\n" +
                "Sampai tiba suatu hari, di mana permaisuri akhirnya akan melahirkan anaknya. Di hari itu, seorang anak laki-laki yang tampan dan berani lahir, ia diberi nama Cindelaras. Cindelaras tumbuh menjadi anak yang pandai berburu.\n" +
                "Ketika ia berburu di hutan, Cindelaras tidak sengaja menemukan telur yang dijatuhkan burung elang. Ia pun mengambilnya dan merawatnya hingga akhirnya telur itu menetas. Ternyata, telur yang sudah dijaga oleh Cindelaras adalah telur ayam. Dari telur itu, muncul seekor ayam jantan, dan Cindelaras sangat menyayangi ayam tersebut. Saat ayam itu tumbuh besar, ayam ini memiliki kokok yang terlihat sangat aneh. Meski begitu, ayam ini merupakan ayam yang sangat penurut. Cindelaras pun mengikutkan ayamnya ke berbagai macam perlombaan dan ia berhasil memenangkan semuanya. Akhirnya, ayam Cindelaras pun jadi semakin terkenal.\n" +
                "Ternyata, ketenaran ayam Cindelaras terdengar hingga ke istana. Raden Putra pun menjadi penasaran dan ia mengundang Cindelaras ke istana. Ia ingin mengadu ayam yang Raden Putra miliki dengan ayam yang Cindelaras miliki.\n" +
                "“Jika aku menang, berikan separuh kekayaanmu,” tantang Cindelaras pada Raden Putra. Tanpa berpikir panjang dan keraguan, Raden Putra menyetujui persyaratan itu. Di akhir pertandingan, ayam Cindelaras terus berhasil memenangkan perlombaan, Raden Putra pun merasa sangat kecewa. Lalu, ia pun bertanya pada Cindelaras tentang asal-usulnya dan bagaimana ia bisa melatih ayam menjadi hebat seperti itu.\n" +
                "Tak disangka-sangka, yang menjawab pertanyaan itu justru ayam Cinderlaras! “Aku adalah ayam jantan yang pandai! Tuanku bernama Cindelaras, anak laki-laki dari Raden Putra,” Raden Putra pun terkejut dan bertanya pada patih untuk memastikannya. Sang patih akhirnya menceritakan yang sebenarnya dan tidak lupa juga ia menyebutkan kejahatan yang sudah dilakukan sang selir.\n" +
                "Raden Putra pun sangat marah dan ia mengusir sang selir yang sudah diangkat menjadi permaisuri itu. Akhirnya, permaisuri yang tinggal di dalam hutan dijemput, dan Raden Putra, permaisuri, serta anaknya—Cindelaras—tinggal bahagia di istana.\n", R.drawable.cinderalas),
        Cerita(2, LEGENDA, "Candi Prambanan", "Kisah Roro Jonggrang bermula saat ayahnya, Raja Prambanan, gugur dari perang melawan Bandung Bondowoso dari Kerajaan Pengging. Bandung Bondowoso secara otomatis langsung menguasai Kerajaan Prambanan.\n" +
                "Di saat bersamaan, Bandung Bondowoso juga ingin menjadikan Roro Jonggrang sebagai permaisurinya. Namun, Roro Jonggrang menolak mentah-mentah lamaran Bandung Bondowoso.\n" +
                "Penolakan Roro Jonggrang tersebut membuat Bandung Bondowoso marah. Ia pun mengurung perempuan cantik itu di dalam istana, bersama Bi Sumi dan dayang-dayang lain.\n" +
                "Setiap hari, Bandung Bondowoso terus mendesak Roro Jonggrang untuk menikah dengannya. Hingga pada suatu hari, Roro Jonggrang pun lelah mendengar permintaan itu dan dia memutuskan untuk melakukan sesuatu.\n" +
                "\"Aku bersedia menjadi permaisurimu, tapi ada syaratnya. Jika kau berhasil memenuhinya, maka aku akan menikah denganmu. Tapi jika kamu gagal, maka izinkanlah aku pergi dari sini,\" kata Roro Jonggrang pada Bandung Bondowoso.\n" +
                "Mendengar permintaan Roro Jonggrang, Bandung Bondowoso tampak senang. Dengan angkuh dia menjawab yakin bisa memenuhi permintaan Roro Jonggrang.\n" +
                "\"Apa pun yang kau minta, pasti akan kuberikan. Jika sampai aku gagal, maka kau tak usah pergi dari sini. Aku yang akan mengembalikan kerajaan ini padamu,\" jawab Bandung Bondowoso.\n" +
                "Roro Jonggrang tersenyum, \"Kalau begitu, buatkan aku seribu candi dalam semalam. Semuanya harus selesai sebelum matahari terbit,\" ujarnya.\n" +
                "Bandung Bondowoso sempat heran dengan permintaan Roro Jonggrang. Tak lama, dia tertawa bahagia.\n" +
                "\"Aku pasti berhasil memenuhi permintaanmu,\" kata Bandung Bondowoso.\n" +
                "Bandung Bondowoso pun langsung beranjak untuk memenuhi permintaan Roro Jonggrang. Ia meminta bantuan pada pasukan jin karena membangun seribu candi dalam waktu semalam adalah pekerjaan mudah bagi bangsa jin.\n" +
                "Benar saja, dalam waktu singkat, bangunan candi mulai tampak. Melihat itu semua, Roro Jonggrang mulai gelisah dan panik.\n" +
                "\"Bi Sumi, kita harus melakukan sesuatu! Lihatlah, candinya hampir siap,\" kata Roro Jonggrang pada Bi Sumi di dalam istana.\n" +
                "Bi Sumi juga tampak panik. Namun, tiba-tiba saja, Bi Sumi memiliki ide untuk membantu Roro Jonggrang.\n" +
                "\"Hamba punya ide. Ayo, ikuti hamba,\" ujar Bi Sumi.\n" +
                "Roro Jonggrang dan Bi Sumi lalu menyelinap ke luar kamar dan menuju ke kamar dayang-dayang yang letaknya tak jauh dari kamar mereka. Bi Sumi lalu memerintahkan para dayang dan pengawal istana yang setia untuk mengumpulkan jerami.\n" +
                "\"Untuk apa, Bi?\" tanya Roro Jonggrang.\n" +
                "Bi Sumi lalu menempelkan telunjuknya di bibir dan berbisik pada Roro Jonggrang, \"Kita akan membakar jerami ini, sehingga langit terkesan menjadi merah, pertanda matahari sudah terbit,\" katanya.\n" +
                "Setelah jeraminya terkumpul, Bi Sumi lalu membakarnya. Dia juga memerintahkan para dayang untuk menumbuk lesung.\n" +
                "Suara lesung yang bertalu-talu, ditambah semburat api yang memecah langit, membuat suasananya mirip pagi hari. Ayam jantan pun tertipu dan berkokok keras memecah suasana hening.\n" +
                "\"Kukuruyukk...kukuruyukkk...\"\n" +
                "Mendengar suara ayam jantan, Bandung Bondowoso dan para jin terkejut. Mereka melihat ke langit yang sudah cukup terang.\n" +
                "\"Wah, ternyata haru sudah pagi. Kami harus pergi!\" teriak para jin sambil bergegas pergi.\n" +
                "Bandung Bodowoso tak berkutik dan membiarkan para jin pergi. Ia lalu memandangi candi buatan para jin dan yakin jumlahnya sudah seribu, sesuai permintaan Roro Jonggrang.\n" +
                "\"Roro Jonggrang tak akan bisa mengelak,\" kata Bandung Bondowoso.\n" +
                "Ia lalu segera mencari Roro Jonggrang untuk melaporkan candi-candi yang sudah dibangunnya. Roro Jonggrag lalu menghitung candi-candi yang sudah selesai.\n" +
                "\"997, 998, 999, dan.... jumlahnya kurang satu!\" kata Roro Jonggrang.\n" +
                "Bandung Bondowoso tak percaya apa yang didengarnya. Ia lalu menghitung sendiri jumlah candi dan ternyata memang benar, candi yang dibangun pasukan jin hanya berjumlah 999.\n" +
                "Bandung Bondowoso sangat kecewa dan marah. Ia tak menyangka bisa gagal memenuhi permintaan Roro Jonggrang.\n" +
                "\"Aku tak pernah kalah. Apa pun yang aku inginkan, pasti akan kudapatkan. Jika aku mau seribu candi, maka aku akan mendapatkannya,\" ujar Bandung Bondowoso.\n" +
                "\"Tapi jumlahnya memang kurang satu. Kau harus menepati janjimu,\" kata Roro Jonggrang yang mulai takut melihat amarah Bandung Bondowoso.\n" +
                "Tak terima disebut kalah, Bandung Bondowoso lalu meminta Roro Jonggrang menjadi candi keseribu. Dengan kesaktiannya, ia mengubah Roro Jonggrang menjadi patung batu.\n" +
                "\"Jika begitu, kau saja yang melengkapi jumlah candi ini. Jadilah kau candi keseribu!\" teriak Bandung Bondowoso.\n" +
                "Patung Roro Jonggrang lalu melengkapi jumlah candi menjadi seribu buah. Sampai sekarang, candi-candi tersebut masih berdiri dengan megah di wilayah Prambanan dan disebut dengan nama Candi Sewu. Kisah Roro Jonggrang pun menjadi cerita rakyat yang terkenal di Indonesia.\n", R.drawable.prambanan),
        Cerita(3, LEGENDA, "Sangkuriang", "Kisah tentang Sangkuriang berawal dari khayangan, di mana ada sepasang dewa dan dewi yang dihukum menjadi  hewan dan menjalani masa hukumannya di bumi. Sang dewa diubah menjadi seekor anjing jantan yang bernama Si Tumang, dan sang dewi menjadi seekor babi hutan betani yang bernama Celeng Wayung Hyang.\n" +
                "Lalu, pada suatu hari, ada seorang raja yang bernama Sungging Perbangkara. Di suatu pagi, saat ia pergi berburu di tengah hutan, tiba-tiba ia ingin buang air dan sang raja membuangnya di batok kelapa. Tidak lama kemudian, Celeng Wayung Hyang datang dalam keadaan haus luar biasa. Ia pun meminum air yang ada di batok kelapa tadi. Tiba-tiba, Celeng Wayung Hyang hamil dan melahirkan seorang putri yang sangat cantik.\n" +
                "Saat Raja Sungging Perbangkara melihatnya, ia langsung menggendong bayi cantik tersebut dan membawanya pulang ke keraton. Sang raja menamakan putri cantiknya Dayang Sumbi atau Rarasati. Dayang Sumbi tumbuh menjadi gadis yang sangat cantik, sehingga banyak raja-raja yang ingin mengantre untuk menjadi suaminya.\n" +
                "Namun, Dayang Sumbi menolak semua lamaran pernikahan. Bahkan, para raja-raja yang memperebutkan Dayang Sumbi ini sampai rela berperang untuk memenangkan hatinya, lho. Karena merasa penat dengan segala lamaran yang menghampirinya, Dayang Sumbi memutuskan untuk mengasingkan dirinya ke hutan. Di dalam hutan, Dayang Sumbi ditemani oleh seekor anjing, yaitu Si Tumang.\n" +
                "Pada suatu hari, saat Dayang Sumbi sedang menenun, kainnya terjatuh dan ia merasa malas untuk mengambilnya. Ia pun membuat janji pada dirinya sendiri bahwa laki-laki mana pun yang mengambilkan kainnya, akan ia nikahkan. Namun, jika perempuan yang menolongnya, akan ia jadikan saudara.\n" +
                "Ternyata, yang mengambil kain Dayang Sumbi adalah Si Tumang! Dayang Sumbi pun tidak mengingkari janjinya, ia menjadikan Si Tumang suaminya. Dari pernikahan ini, Dayang Sumbi dan Si Tumang melahirkan seorang anak laki-laki yang bernama Sangkuriang.\n" +
                "Saat Sangkuriang tumbuh menjadi seorang remaja, Dayang Sumbi memberikannya tugas untuk berburu rusa. Sangkuriang pergi berburu ditemani oleh Si Tumang, mereka dusuk menunggu hewan-hewan mangsa melewati mereka tapi tidak ada satu pun juga yang datang. Tiba-tiba, Sangkuriang melihat seekor babi hutan yang gemuk, Sangkuriang pun menyuruh Si Tumang mengejar dan menangkapnya. Namun, Si Tumang menolak karena babi hutan yang dilihat Sangkuriang adalah Celeng Wayung Hyang.\n" +
                "Sangkuriang pun mengancam Si Tumang dengan anak panahnya dan ia tidak sengaja melepaskannya. Ia pun tidak sengaja membunuh Si Tumang. Sangkuriang merasa panik dan ia menyemelih Si Tumang untuk mengambil hatinya. Setelah itu, Sangkuriang kembali pulang dan menyerahkan hati tersebut ke ibunya. Mengira bahwa yang diterimanya adalah hati rusa, Dayang Sumbi pun memasak dan memakannya. Namun, setelah mengetahui yang ia makan adalah hati Si Tumang, Dayang Sumbi pun marah besar kepada Sangkuriang.\n" +
                "Dayang Sumbi memukul kepala putranya dengan sendok nasi yang terbuat dari kayu hingga kepala Sangkuriang terluka. Sangkuriang merasa takut, ia pun akhirnya meninggalkan rumah dan Dayang Sumbi.\n" +
                "Setelah sekian lama pergi dari rumah, Sangkuriang tumbuh menjadi laki-laki dewasa yang kuat dan sakti. Pada suatu hari, ia mengembara hingga tidak menyadari berjalan sampai ke tempat di mana Dayang Sumbi berada. Sangkuriang pun jatuh hati terhadap kecantikan Dayang Sumbi dan tidak mengetahui bahwa wanita yang dicintainya itu adalah ibunya sendiri.\n" +
                "Saat Sangkuriang berniat menikahinya, Dayang Sumbi tentu saja menolak karena ia mengetahuiu bahwa pria yang hendak melamarnya adalah putranya sendiri. Dayang Sumbi pun memberikan syarat yang mustahil kepada Sangkuriang apabila ingin menjadi suaminya, karena ia yakin anaknya tidak bisa memenuhi keinginannya ini.\n" +
                "Permintaan Dayang Sumbi adalah ia ingin dibuatkan perahu dan telaga yangg harus selesai hanya dalam semalam dengan membendung aliran Sungai Citarum. Nyatanya, syarat itu disanggupi oleh Sangkuriang. Dayang Sumbi pun takut Sangkuriang bisa menyelesaikannya dan memohon kepada Sang Hyangg Tunggal agar menggagalkan usaha Sangkuriang. Ia juga memukulkan alu ke lesung, seolah-olah sedang menumbuk padi agar menjadi pertanda bahwa fajar telah tiba.\n" +
                "Akhirnya, para makhluk halus anak buah Sangkuriang pun menjadi ketakutan dan pergi sebelum menyelesaikan tugasnya karena mengira matahari akan segera bersinar. Karena gagal memenuhi persyaratan Dayang Sumbi, Sangkuriang pun marah, mengamuk, dan menendang perahu yang dibuatnya ke arah utara.\n" +
                "Dalam sekejap, perahu yang jatuh menelungkup dan berubah menjadi Gunung Tangkuban Perahu. Setelah itu, Sangkuriang masih mengejar Dayang Sumbi hingga ke Gunung Putri. Namun, Sang Hyang Tunggal segera menolong dan mengubah Dayang Sumbi menjadi setangkai Bunga Jaksi agar lolos dari kejaran Sangkuriang. Sangkuriang pun tidak berhasil menemukan Dayang Sumbi, dan pada akhirnya Sangkuriang menghilang ke alam gaib.\n", R.drawable.sangkuriang),
        Cerita(4, MITOLOGI, "Perang Troya", "Perang Troya adalah salah satu perang terbesar yang pernah terjadi dalam mitologi Yunani. Pada perang itu, Bangsa Akhaia (Yunani) menyerang kota Troya. Reruntuhan kota Troya sendiri kini telah ditemukan di Asia Minor (Turki). Perang besar yang menghabiskan banyak korban manusia itu dipicu oleh perbuatan para dewa.\n" +
                "Semua dewa-dewi dan orang penting diundang ke pernikahan Peleus dan Thetis (orang tua Akhilles). Hanya dewi Eris (dewi perselisihan) yang tidak diundang. Dewa Eris marah dan melempar sebuah apel ke tengah-tengah pesta, apel tersebut beruliskan kallistei (\"untuk yang tercantik\"). Afrodit, Hera, dan Athena mengklaim sebagai pemilik apel tersebut dan sebagai dewi tercantik.\n" +
                "Ketiga dewi tersebut mendatangi Zeus untuk menentukan siapa yang berhak memiliki apel emas itu. Zeus tidak ingin memihak siapapun dan menyuruh mereka untuk meminta keputusan pada Paris. Hera berusaha menyuap Paris dengan kekayaan, Athena berjanji akan menjadikan Paris jenderal yang berjaya dan terkenal, sementara Afrodit menawarkan wanita tercantik di dunia (Helene). Paris akhirnya memilih Helene dan dengan demikian memilih Afrodit sebagai dewi tercantik. Helene sendiri sebenarnya telah menjadi istri Menelaos, raja Sparta tetapi Eros, dewa cinta anak Afrodit, memanah Helene dengan panah cinta sampai akhirnya Helene jatuh cinta pada Paris. dan bersedia untuk dibawa kabur ke Troya. Suami Helene, Menelaos, marah besar. Dengan didukung oleh saudaranya, Agamemnon raja Mikenai dan raja-raja Yunani lainnya, Menelaos menyerang kota Troya.\n" +
                "Perang Troya berlangsung selama sepuluh tahun. Banyak pahlawan yang terlibat dalam perang ini, di antaranya adalah Akhilles, Odisseus, Aias, dan Diomedes dari pihak Yunani, dan Hektor serta Paris dari pihak Troya. Setelah berjuang bertahun-tahun dan belum bisa juga menjebol benteng Troya, pasukan Yunani mulai frustasi. Tetapi kemudian Odisseus mencetuskan ide cemerlang. Pasukan Yunani membangun sebuah kuda kayu raksasa yang diisi oleh beberapa prajurit. Pasukan Yunani kemudian meninggalkan kuda itu lalu pura-pura pergi meninggalkan Troya. Pasukan Troya melihat pasukan Yunani mundur dan mengira mereka telah menyerah. Kuda raksasa itu dikira sebaagi pernyataan kekalahan dari yunani. Orang-orang Troya membawa kuda itu ke dalam kota mereka dan merayakan kemenangan mereka. Pada malam harinya, para prajurit yang bersembunyi di dalam kuda keluar dan membuka gerbang kota Troya sehingga pasukan Yunani bisa masuk. Pasukan Yunani pun meluluhlantakan kota Troya. Seusai perang, Menelaos berhasil mendapatkan kembali istrinya sementara beberapa orang Troya, dengan dipimpin oleh Aineias, berhasil menyelamatkan diri.\n", R.drawable.perang_troya),
        Cerita(5, MITOLOGI, "Daidalos dan Ikaros", "Daidalos adalah seorang perajin, seniman, dan penemu yang tinggal di kota Athena. Daidalos memiliki seorang keponakan bernama Talos. Di bawah bimbingan Daidalos dan ditambah bakat yang luar biasa, Talos punya kesempatan untuk menjadi lebih dari pamannya. Namun Daidalos takut bakat Talos itu akan menyaingi keahliannya. Akhirnya ketika Daidalos dan Talos sedang berada di Akropolis, Daidalos membunuh Talos dengan cara melemparnya dari Akropolis.\n" +
                "Akibat perbuatannya itu dia diusir dari Athena dan pindah ke Kreta, Di sana dia bekerja pada raja Minos. Suatu ketika Pasifae, istri Minos, jatuh cinta pada Banteng Kreta dan meminta bantuan Daidalos supaya membuatkannya sebuah replika banteng betina. Setelah jadi, Pasifae masuk ke dalam replika banteng itu dan bersetubuh dengan banteng Kreta. Hasil persetubuhan itu adalah Minotaur, makhluk buas setengah manusia setengah banteng.\n" +
                "Minos lalu menyuruh Daidalos membuat sebuah tempat untuk mengurung Minotaur dan Daidalos pun merancang labirin, sebuah tempat yang penuh jalan dan membingungkan. Setelah selesai, Minos mengurung Daidalos dan putranya Ikaros di menara yang tinggi untuk mencegah tersebarnya rahasia labirin.\n" +
                "Daidalos dan Ikaros tidak bisa kabur lewat laut karena semua kapal diawasi dengan ketat dan tak ada yang boleh berlayar tanpa izin. Karena Minos menguasai darat dan laut, maka Daidalos memutuskan untuk kabur lewat udara.\n" +
                "Daidalos kemudian berusaha membuat sayap dari bulu untuknya dan putranya. Bulu-bulu itu dia ikat dengan kuat, bulu berukuran besar diikat dengan benang sedangkan yang kecil disambungkan dengan lilin. Setelah selesai, mereka pun memakainya. Sebelum terbang, Daidalos memperingatkan Ikaros untuk tidak terbang terlalu rendah atau terlalu tinggi, dan mereka pun akhirnya terbang keluar dari menara.\n" +
                "Mereka terbang di atas lautan dan Ikaros menjadi terlalu senang sampai-sampai Ikaros terbang terlalu tinggi. Karena ulahnya itu, lilin pada sayapnya meleleh oleh panas matahari sehingga Ikaros akhirnya terjatuh ke laut. Untuk mengenang putranya, pulau di dekat tempat Ikaros jatuh dinamai pulau Ikaria oleh Daidalos.\n", R.drawable.ikarus),
    )


}